/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui_kuisioner_udpk;

import javax.swing.JScrollPane;

/**
 *
 * @author LENOVO
 */
public class kuesionerPanel extends javax.swing.JPanel {
    
    private JScrollPane contentScrollPane;
    private Perusahaan perusahaan;
    /**
     * Creates new form kuesionerPanel
     */
    public kuesionerPanel(JScrollPane contentScrollPane, Perusahaan perusahaan) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
        this.perusahaan = perusahaan;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulKuesionerPanel = new javax.swing.JLabel();
        statusPerusahaanLabel = new javax.swing.JLabel();
        kualifikasiPerusahaanLabel = new javax.swing.JLabel();
        badanHukumLabel = new javax.swing.JLabel();
        jenisBoronganLabel = new javax.swing.JLabel();
        statusPerusahaanComboBox = new javax.swing.JComboBox<>();
        kualifikasiPerusahaanComboBox = new javax.swing.JComboBox<>();
        badanHukumComboBox = new javax.swing.JComboBox<>();
        jenisBoronganField = new javax.swing.JTextField();
        bidangPekerjaanUtamaLabel = new javax.swing.JLabel();
        bidangPekerjaanComboBox = new javax.swing.JComboBox<>();
        tempatUsahaLabel = new javax.swing.JLabel();
        tempatUsahaComboBox = new javax.swing.JComboBox<>();
        tempatUsahaLainnya = new javax.swing.JTextField();
        banyakPekerjaLabel = new javax.swing.JLabel();
        jmlPekerjaLakiField = new javax.swing.JTextField();
        jmlPekerjaPerempuanField = new javax.swing.JTextField();
        jmlPekerja = new javax.swing.JTextField();
        jmlPekerjaLakiLabel = new javax.swing.JLabel();
        jmlPekerjaPerempuanLabel = new javax.swing.JLabel();
        jmlPekerjaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lanjutkanButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();

        judulKuesionerPanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulKuesionerPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulKuesionerPanel.setText("Pengisian Kuesioner UDPK");

        statusPerusahaanLabel.setText("Status Perusahaan/Usaha Saat Dikunjungi       :");

        kualifikasiPerusahaanLabel.setText("Kualifikasi Perusahaan/Usaha (Gred)                 :");

        badanHukumLabel.setText("Badan Hukum/Badan Usaha                             :");

        jenisBoronganLabel.setText("Isikan Jenis borongan Pekerjaan Utama Yang Biasa Dikerjakan:");

        statusPerusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif Lama", "Aktif Baru", "Tutup", "Tidak Ditemukan", "Bukan Konstruksi" }));

        kualifikasiPerusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gred 1", "Gred 2", "Gred 3", "Gred 4", "Gred 5", "Gred 6", "Gred 7", "Non Gred" }));

        badanHukumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT. Persero", "PT.", "CV", "Firma", "Koperasi", "Perorangan", "Lainnya" }));

        bidangPekerjaanUtamaLabel.setText("Bidang Pekerjaan Utama                                   :");

        bidangPekerjaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Konstruksi Gedung", "Konstruksi Sipil", "Konstruksi Khusus" }));

        tempatUsahaLabel.setText("Tempat Usaha                                                   :");

        tempatUsahaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kantor", "Rumah Tinggal", "Rukan", "Lainnya" }));

        tempatUsahaLainnya.setEditable(false);

        banyakPekerjaLabel.setText("Banyak Pekerja Tetap                      :");

        jmlPekerja.setEditable(false);

        jmlPekerjaLakiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPekerjaLakiLabel.setText("Laki-laki");

        jmlPekerjaPerempuanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPekerjaPerempuanLabel.setText("Perempuan");

        jmlPekerjaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPekerjaLabel.setText("Total");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setText("(jumlah pekerja tetap pada saat pencacahan)");

        lanjutkanButton.setBackground(new java.awt.Color(102, 255, 102));
        lanjutkanButton.setForeground(new java.awt.Color(255, 255, 255));
        lanjutkanButton.setText("Lanjutkan");
        lanjutkanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutkanButtonActionPerformed(evt);
            }
        });

        batalButton.setBackground(new java.awt.Color(255, 51, 51));
        batalButton.setForeground(new java.awt.Color(255, 255, 255));
        batalButton.setText("Batal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jmlPekerjaLakiField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(banyakPekerjaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jmlPekerjaLakiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jmlPekerjaPerempuanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmlPekerjaPerempuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jmlPekerja, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jmlPekerjaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(batalButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(lanjutkanButton))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(kualifikasiPerusahaanLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(kualifikasiPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(statusPerusahaanLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(statusPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(badanHukumLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(badanHukumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jenisBoronganLabel)
                                        .addComponent(jenisBoronganField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bidangPekerjaanUtamaLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(bidangPekerjaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tempatUsahaLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(tempatUsahaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tempatUsahaLainnya))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judulKuesionerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulKuesionerPanel)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusPerusahaanLabel)
                    .addComponent(statusPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kualifikasiPerusahaanLabel)
                    .addComponent(kualifikasiPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badanHukumLabel)
                    .addComponent(badanHukumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jenisBoronganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisBoronganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidangPekerjaanUtamaLabel)
                    .addComponent(bidangPekerjaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempatUsahaLabel)
                    .addComponent(tempatUsahaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempatUsahaLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banyakPekerjaLabel)
                    .addComponent(jmlPekerjaLakiLabel)
                    .addComponent(jmlPekerjaPerempuanLabel)
                    .addComponent(jmlPekerjaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jmlPekerjaLakiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmlPekerjaPerempuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmlPekerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanjutkanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lanjutkanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutkanButtonActionPerformed
        // TODO add your handling code here:
        QuestionaireData qd = new QuestionaireData();
        qd.setPerusahaan(perusahaan);
    }//GEN-LAST:event_lanjutkanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> badanHukumComboBox;
    private javax.swing.JLabel badanHukumLabel;
    private javax.swing.JLabel banyakPekerjaLabel;
    private javax.swing.JButton batalButton;
    private javax.swing.JComboBox<String> bidangPekerjaanComboBox;
    private javax.swing.JLabel bidangPekerjaanUtamaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jenisBoronganField;
    private javax.swing.JLabel jenisBoronganLabel;
    private javax.swing.JTextField jmlPekerja;
    private javax.swing.JLabel jmlPekerjaLabel;
    private javax.swing.JTextField jmlPekerjaLakiField;
    private javax.swing.JLabel jmlPekerjaLakiLabel;
    private javax.swing.JTextField jmlPekerjaPerempuanField;
    private javax.swing.JLabel jmlPekerjaPerempuanLabel;
    private javax.swing.JLabel judulKuesionerPanel;
    private javax.swing.JComboBox<String> kualifikasiPerusahaanComboBox;
    private javax.swing.JLabel kualifikasiPerusahaanLabel;
    private javax.swing.JButton lanjutkanButton;
    private javax.swing.JComboBox<String> statusPerusahaanComboBox;
    private javax.swing.JLabel statusPerusahaanLabel;
    private javax.swing.JComboBox<String> tempatUsahaComboBox;
    private javax.swing.JLabel tempatUsahaLabel;
    private javax.swing.JTextField tempatUsahaLainnya;
    // End of variables declaration//GEN-END:variables
}
