/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_kuisioner_udpk;

/**
 *
 * @author U53R
 */
public class kuisionerPanel extends javax.swing.JFrame {

    /**
     * Creates new form kuisionerPanel
     */
    public kuisionerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        judulKuesionerPanel = new javax.swing.JLabel();
        statusPerusahaanLabel = new javax.swing.JLabel();
        kualifikasiPerusahaanLabel = new javax.swing.JLabel();
        badanHukumLabel = new javax.swing.JLabel();
        jenisBoronganLabel = new javax.swing.JLabel();
        statusPerusahaanComboBox = new javax.swing.JComboBox<>();
        kualifikasiPerusahaanComboBox = new javax.swing.JComboBox<>();
        badanHukumComboBox = new javax.swing.JComboBox<>();
        jenisBoronganField = new javax.swing.JTextField();
        bidangPekerjaanUtamaLabel = new javax.swing.JLabel();
        bidangPekerjaanComboBox = new javax.swing.JComboBox<>();
        tempatUsahaLabel = new javax.swing.JLabel();
        tempatUsahaComboBox = new javax.swing.JComboBox<>();
        tempatUsahaLainnya = new javax.swing.JTextField();
        banyakPekerjaLabel = new javax.swing.JLabel();
        jmlPekerjaLakiField = new javax.swing.JTextField();
        jmlPekerjaPerempuanField = new javax.swing.JTextField();
        jmlPekerja = new javax.swing.JTextField();
        jmlPekerjaLakiLabel = new javax.swing.JLabel();
        jmlPekerjaPerempuanLabel = new javax.swing.JLabel();
        jmlPekerjaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contactPersonLabel = new javax.swing.JLabel();
        namaCPLabel = new javax.swing.JLabel();
        namaCPField = new javax.swing.JTextField();
        jabatanCPLabel = new javax.swing.JLabel();
        jabatanCPField = new javax.swing.JTextField();
        tanggalCPLabel = new javax.swing.JLabel();
        tanggalCPField = new javax.swing.JFormattedTextField();
        pencacahLabel = new javax.swing.JLabel();
        namaPencacahLabel = new javax.swing.JLabel();
        namaPencacahField = new javax.swing.JTextField();
        jabatanPencacahLabel = new javax.swing.JLabel();
        jabatanPencacahField = new javax.swing.JTextField();
        tanggalPencacahLabel = new javax.swing.JLabel();
        tanggalPencacahField = new javax.swing.JFormattedTextField();
        pengawasLabel = new javax.swing.JLabel();
        namaPengawasLabel = new javax.swing.JLabel();
        namaPengawasField = new javax.swing.JTextField();
        jabatanPengawasLabel = new javax.swing.JLabel();
        jabatanPengawasField = new javax.swing.JTextField();
        tanggalPencacahLabel1 = new javax.swing.JLabel();
        tanggalPengawasField = new javax.swing.JFormattedTextField();
        lanjutkanButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulKuesionerPanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulKuesionerPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulKuesionerPanel.setText("Pengisian Kuesioner UDPK");

        statusPerusahaanLabel.setText("Status Perusahaan/Usaha Saat Dikunjungi       :");

        kualifikasiPerusahaanLabel.setText("Kualifikasi Perusahaan/Usaha (Gred)                 :");

        badanHukumLabel.setText("Badan Hukum/Badan Usaha                             :");

        jenisBoronganLabel.setText("Isikan Jenis borongan Pekerjaan Utama Yang Biasa Dikerjakan:");

        statusPerusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif Lama", "Aktif Baru", "Tutup", "Tidak Ditemukan", "Bukan Konstruksi" }));

        kualifikasiPerusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gred 1", "Gred 2", "Gred 3", "Gred 4", "Gred 5", "Gred 6", "Gred 7", "Non Gred" }));

        badanHukumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT. Persero", "PT.", "CV", "Firma", "Koperasi", "Perorangan", "Lainnya" }));

        bidangPekerjaanUtamaLabel.setText("Bidang Pekerjaan Utama                                   :");

        bidangPekerjaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Konstruksi Gedung", "Konstruksi Sipil", "Konstruksi Khusus" }));

        tempatUsahaLabel.setText("Tempat Usaha                                                   :");

        tempatUsahaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kantor", "Rumah Tinggal", "Rukan", "Lainnya" }));

        tempatUsahaLainnya.setEditable(false);

        banyakPekerjaLabel.setText("Banyak Pekerja Tetap                      :");

        jmlPekerja.setEditable(false);

        jmlPekerjaLakiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPekerjaLakiLabel.setText("Laki-laki");

        jmlPekerjaPerempuanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPekerjaPerempuanLabel.setText("Perempuan");

        jmlPekerjaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlPekerjaLabel.setText("Total");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setText("(jumlah pekerja tetap pada saat pencacahan)");

        contactPersonLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactPersonLabel.setText("Contact Person");

        namaCPLabel.setText("Nama                   :");

        jabatanCPLabel.setText("Jabatan                :");

        tanggalCPLabel.setText("Tanggal                :");

        tanggalCPField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        pencacahLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pencacahLabel.setText("Pencacah");

        namaPencacahLabel.setText("Nama                   :");

        jabatanPencacahLabel.setText("Jabatan                :");

        tanggalPencacahLabel.setText("Tanggal                :");

        tanggalPencacahField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        pengawasLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pengawasLabel.setText("Pengawas");

        namaPengawasLabel.setText("Nama                   :");

        jabatanPengawasLabel.setText("Jabatan                :");

        tanggalPencacahLabel1.setText("Tanggal                :");

        tanggalPengawasField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        lanjutkanButton.setBackground(new java.awt.Color(102, 255, 102));
        lanjutkanButton.setForeground(new java.awt.Color(255, 255, 255));
        lanjutkanButton.setText("Lanjutkan");

        batalButton.setBackground(new java.awt.Color(255, 51, 51));
        batalButton.setForeground(new java.awt.Color(255, 255, 255));
        batalButton.setText("Batal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactPersonLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jmlPekerjaLakiField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(banyakPekerjaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jmlPekerjaLakiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jmlPekerjaPerempuanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmlPekerjaPerempuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jmlPekerja, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jmlPekerjaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(pencacahLabel)
                            .addComponent(pengawasLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jabatanCPLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jabatanCPField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namaCPLabel)
                                .addGap(84, 84, 84)
                                .addComponent(namaCPField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaPengawasLabel)
                                    .addComponent(tanggalPencacahLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalPencacahField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaPengawasField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(namaPencacahLabel)
                                                .addComponent(tanggalCPLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jabatanPencacahLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tanggalCPField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namaPencacahField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jabatanPencacahField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jabatanPengawasLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jabatanPengawasField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tanggalPencacahLabel1)
                                .addGap(84, 84, 84)
                                .addComponent(tanggalPengawasField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(batalButton)
                                .addGap(18, 18, 18)
                                .addComponent(lanjutkanButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(kualifikasiPerusahaanLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(kualifikasiPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(statusPerusahaanLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(statusPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(badanHukumLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(badanHukumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jenisBoronganLabel)
                                .addComponent(jenisBoronganField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bidangPekerjaanUtamaLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(bidangPekerjaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tempatUsahaLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(tempatUsahaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tempatUsahaLainnya))))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulKuesionerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulKuesionerPanel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusPerusahaanLabel)
                    .addComponent(statusPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kualifikasiPerusahaanLabel)
                    .addComponent(kualifikasiPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badanHukumLabel)
                    .addComponent(badanHukumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jenisBoronganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisBoronganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidangPekerjaanUtamaLabel)
                    .addComponent(bidangPekerjaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempatUsahaLabel)
                    .addComponent(tempatUsahaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempatUsahaLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banyakPekerjaLabel)
                    .addComponent(jmlPekerjaLakiLabel)
                    .addComponent(jmlPekerjaPerempuanLabel)
                    .addComponent(jmlPekerjaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jmlPekerjaLakiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmlPekerjaPerempuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmlPekerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addComponent(contactPersonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaCPLabel)
                    .addComponent(namaCPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatanCPLabel)
                    .addComponent(jabatanCPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalCPLabel)
                    .addComponent(tanggalCPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pencacahLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPencacahLabel)
                    .addComponent(namaPencacahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatanPencacahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jabatanPencacahLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalPencacahLabel)
                    .addComponent(tanggalPencacahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pengawasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPengawasLabel)
                    .addComponent(namaPengawasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatanPengawasLabel)
                    .addComponent(jabatanPengawasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalPencacahLabel1)
                    .addComponent(tanggalPengawasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanjutkanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuisionerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuisionerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuisionerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuisionerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuisionerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> badanHukumComboBox;
    private javax.swing.JLabel badanHukumLabel;
    private javax.swing.JLabel banyakPekerjaLabel;
    private javax.swing.JButton batalButton;
    private javax.swing.JComboBox<String> bidangPekerjaanComboBox;
    private javax.swing.JLabel bidangPekerjaanUtamaLabel;
    private javax.swing.JLabel contactPersonLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jabatanCPField;
    private javax.swing.JLabel jabatanCPLabel;
    private javax.swing.JTextField jabatanPencacahField;
    private javax.swing.JLabel jabatanPencacahLabel;
    private javax.swing.JTextField jabatanPengawasField;
    private javax.swing.JLabel jabatanPengawasLabel;
    private javax.swing.JTextField jenisBoronganField;
    private javax.swing.JLabel jenisBoronganLabel;
    private javax.swing.JTextField jmlPekerja;
    private javax.swing.JLabel jmlPekerjaLabel;
    private javax.swing.JTextField jmlPekerjaLakiField;
    private javax.swing.JLabel jmlPekerjaLakiLabel;
    private javax.swing.JTextField jmlPekerjaPerempuanField;
    private javax.swing.JLabel jmlPekerjaPerempuanLabel;
    private javax.swing.JLabel judulKuesionerPanel;
    private javax.swing.JComboBox<String> kualifikasiPerusahaanComboBox;
    private javax.swing.JLabel kualifikasiPerusahaanLabel;
    private javax.swing.JButton lanjutkanButton;
    private javax.swing.JTextField namaCPField;
    private javax.swing.JLabel namaCPLabel;
    private javax.swing.JTextField namaPencacahField;
    private javax.swing.JLabel namaPencacahLabel;
    private javax.swing.JTextField namaPengawasField;
    private javax.swing.JLabel namaPengawasLabel;
    private javax.swing.JLabel pencacahLabel;
    private javax.swing.JLabel pengawasLabel;
    private javax.swing.JComboBox<String> statusPerusahaanComboBox;
    private javax.swing.JLabel statusPerusahaanLabel;
    private javax.swing.JFormattedTextField tanggalCPField;
    private javax.swing.JLabel tanggalCPLabel;
    private javax.swing.JFormattedTextField tanggalPencacahField;
    private javax.swing.JLabel tanggalPencacahLabel;
    private javax.swing.JLabel tanggalPencacahLabel1;
    private javax.swing.JFormattedTextField tanggalPengawasField;
    private javax.swing.JComboBox<String> tempatUsahaComboBox;
    private javax.swing.JLabel tempatUsahaLabel;
    private javax.swing.JTextField tempatUsahaLainnya;
    // End of variables declaration//GEN-END:variables
}
