/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui_kuisioner_udpk;

/**
 *
 * @author briel
 */
public class tambahPengawas extends javax.swing.JPanel {

    /**
     * Creates new form tambahPengawas
     */
    public tambahPengawas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelKeseluruhan2 = new javax.swing.JPanel();
        LogoBPS2 = new javax.swing.JLabel();
        Garuda2 = new javax.swing.JLabel();
        Indonesia2 = new javax.swing.JLabel();
        PanelRahasia2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        UDP = new javax.swing.JLabel();
        PanelTahun = new javax.swing.JPanel();
        Tahun = new javax.swing.JLabel();
        PanelKonstruksi = new javax.swing.JPanel();
        Konstruksi = new javax.swing.JLabel();
        NamaKuesioner = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Jabatan = new javax.swing.JLabel();
        TextNama = new javax.swing.JTextField();
        BPS = new javax.swing.JLabel();
        TextJabatan = new javax.swing.JTextField();
        TambahPengawas = new javax.swing.JLabel();
        TambahButton = new javax.swing.JButton();

        PanelKeseluruhan2.setBackground(new java.awt.Color(255, 255, 255));

        LogoBPS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_kuisioner_udpk/LogoBPS.jpg"))); // NOI18N

        Garuda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_kuisioner_udpk/Gambar1.jpg"))); // NOI18N

        Indonesia2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Indonesia2.setText("REPUBLIK INDONESIA");

        PanelRahasia2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel4.setBackground(new java.awt.Color(255, 204, 153));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("RAHASIA");

        javax.swing.GroupLayout PanelRahasia2Layout = new javax.swing.GroupLayout(PanelRahasia2);
        PanelRahasia2.setLayout(PanelRahasia2Layout);
        PanelRahasia2Layout.setHorizontalGroup(
            PanelRahasia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRahasia2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelRahasia2Layout.setVerticalGroup(
            PanelRahasia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRahasia2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UDP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UDP.setText("UDP");

        PanelTahun.setBackground(new java.awt.Color(0, 0, 0));

        Tahun.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Tahun.setForeground(new java.awt.Color(255, 255, 255));
        Tahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tahun.setText("2014");

        javax.swing.GroupLayout PanelTahunLayout = new javax.swing.GroupLayout(PanelTahun);
        PanelTahun.setLayout(PanelTahunLayout);
        PanelTahunLayout.setHorizontalGroup(
            PanelTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTahunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTahunLayout.setVerticalGroup(
            PanelTahunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tahun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        PanelKonstruksi.setBackground(new java.awt.Color(0, 0, 0));

        Konstruksi.setBackground(new java.awt.Color(0, 0, 0));
        Konstruksi.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Konstruksi.setForeground(new java.awt.Color(255, 255, 255));
        Konstruksi.setText("Konstruksi");

        javax.swing.GroupLayout PanelKonstruksiLayout = new javax.swing.GroupLayout(PanelKonstruksi);
        PanelKonstruksi.setLayout(PanelKonstruksiLayout);
        PanelKonstruksiLayout.setHorizontalGroup(
            PanelKonstruksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKonstruksiLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(Konstruksi)
                .addContainerGap())
        );
        PanelKonstruksiLayout.setVerticalGroup(
            PanelKonstruksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Konstruksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        NamaKuesioner.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NamaKuesioner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaKuesioner.setText("UPDATING DIREKTORI PERUSAHAAN/USAHA KONSTRUKSI");
        NamaKuesioner.setToolTipText("");
        NamaKuesioner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Nama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Nama.setText("Nama");

        Jabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Jabatan.setText("Jabatan");

        TextNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        TextNama.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        TextNama.setSelectionColor(new java.awt.Color(255, 153, 51));
        TextNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNamaActionPerformed(evt);
            }
        });

        BPS.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        BPS.setForeground(new java.awt.Color(0, 0, 204));
        BPS.setText("BADAN PUSAT STATISTIK");

        TextJabatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextJabatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        TextJabatan.setSelectionColor(new java.awt.Color(255, 153, 51));
        TextJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextJabatanActionPerformed(evt);
            }
        });

        TambahPengawas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TambahPengawas.setText("Tambah Pengawas");

        TambahButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TambahButton.setText("Tambahkan");
        TambahButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        TambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKeseluruhan2Layout = new javax.swing.GroupLayout(PanelKeseluruhan2);
        PanelKeseluruhan2.setLayout(PanelKeseluruhan2Layout);
        PanelKeseluruhan2Layout.setHorizontalGroup(
            PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                        .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(Indonesia2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                            .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelRahasia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Garuda2)
                                .addGap(88, 88, 88)))
                        .addComponent(UDP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelKonstruksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                        .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKeseluruhan2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BPS)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKeseluruhan2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TambahPengawas)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKeseluruhan2Layout.createSequentialGroup()
                            .addComponent(NamaKuesioner)
                            .addGap(35, 35, 35)))
                    .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                        .addComponent(LogoBPS2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        PanelKeseluruhan2Layout.setVerticalGroup(
            PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKeseluruhan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKeseluruhan2Layout.createSequentialGroup()
                        .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelRahasia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Garuda2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Indonesia2))
                    .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(UDP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelKeseluruhan2Layout.createSequentialGroup()
                            .addComponent(PanelKonstruksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PanelTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaKuesioner)
                .addGap(28, 28, 28)
                .addComponent(TambahPengawas)
                .addGap(8, 8, 8)
                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(PanelKeseluruhan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoBPS2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambahButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BPS))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelKeseluruhan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelKeseluruhan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNamaActionPerformed

    private void TextJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextJabatanActionPerformed

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BPS;
    private javax.swing.JLabel Garuda2;
    private javax.swing.JLabel Indonesia2;
    private javax.swing.JLabel Jabatan;
    private javax.swing.JLabel Konstruksi;
    private javax.swing.JLabel LogoBPS2;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NamaKuesioner;
    private javax.swing.JPanel PanelKeseluruhan2;
    private javax.swing.JPanel PanelKonstruksi;
    private javax.swing.JPanel PanelRahasia2;
    private javax.swing.JPanel PanelTahun;
    private javax.swing.JLabel Tahun;
    private javax.swing.JButton TambahButton;
    private javax.swing.JLabel TambahPengawas;
    private javax.swing.JTextField TextJabatan;
    private javax.swing.JTextField TextNama;
    private javax.swing.JLabel UDP;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
