/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui_kuisioner_udpk;

/**
 *
 * @author U53R
 */

import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
public class ViewDatabasePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDatabasePanel
     */
    private JScrollPane contentScrollPane;
    
    public ViewDatabasePanel(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
        loadTableData();
        clearForm();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        databaseTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        tampilButton = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("UPDATING DIREKTORI PERUSAHAAN KONTRUKSI");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_kuisioner_udpk/garuda.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_kuisioner_udpk/Logo BPS -.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("DATABASE");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        databaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KIP", "Nama Perusahaan", "Pencacah", "Pengawas"
            }
        ));
        databaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databaseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(databaseTable);

        deleteButton.setBackground(new java.awt.Color(255, 51, 0));
        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        tampilButton.setBackground(new java.awt.Color(51, 0, 153));
        tampilButton.setForeground(new java.awt.Color(255, 255, 255));
        tampilButton.setText("Tampilkan");
        tampilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))))
                            .addComponent(jLabel4))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(325, 325, 325)
                    .addComponent(deleteButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tampilButton)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(573, 573, 573)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteButton)
                        .addComponent(tampilButton))
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = databaseTable.getSelectedRow();
        
        // Memastikan bahwa baris yang dipilih valid (tidak -1)
        if (selectedRow != -1) {
            // Mengambil KIP dari baris yang dipilih
            String KIP = (String) databaseTable.getValueAt(selectedRow, 0);

            // Menampilkan dialog konfirmasi
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah kamu yakin akan menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            // Jika pengguna mengonfirmasi penghapusan
            if (confirm == JOptionPane.YES_OPTION) {
                // Hapus data dari database berdasarkan KIP
                Database.getInstance().deletePerusahaan(KIP);
                Database.getInstance().deleteKuisioner(KIP);
                // Perbarui tampilan tabel
                loadTableData();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tampilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilButtonActionPerformed
        // Get the selected row index
        int selectedRowIndex = databaseTable.getSelectedRow();

        // Ensure a row is selected
        if (selectedRowIndex != -1) {
            // Get the KIP from the selected row
            String KIP = (String) databaseTable.getValueAt(selectedRowIndex, 0);
            // Retrieve the Perusahaan object from the database using KIP
            Perusahaan perusahaan = Database.getInstance().getPerusahaanByKIP(KIP);
            contentScrollPane.setViewportView(new ViewPanel(contentScrollPane, perusahaan));
        } else {
            // If no row is selected, display a message
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tampilButtonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void databaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseTableMouseClicked
        // Mengambil baris yang dipilih
        int selectedRow = databaseTable.getSelectedRow();

        // Memastikan bahwa baris yang dipilih valid (tidak -1)
        if (selectedRow != -1) {
            // Menampilkan tombol delete dan tampil
            deleteButton.setVisible(true);
            tampilButton.setVisible(true);
        } else {
            // Jika tidak ada baris yang dipilih, sembunyikan tombol delete dan tampil
            deleteButton.setVisible(false);
            tampilButton.setVisible(false);
        }
            
    }//GEN-LAST:event_databaseTableMouseClicked
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) databaseTable.getModel();
        model.setRowCount(0);  // Menghapus semua baris yang ada pada tabel

        // Mengambil data dari instance Database
        List<Perusahaan> perusahaanList = Database.getInstance().getPerusahaanList();
        List<QuestionaireData> kuisionerList = Database.getInstance().getKuisionerList();

        // Memasukkan data ke dalam tabel
        for (int i = 0; i < perusahaanList.size(); i++) {
            Perusahaan perusahaan = perusahaanList.get(i);
            QuestionaireData kuisioner = kuisionerList.get(i);

            model.addRow(new Object[]{
                perusahaan.getKIP(),
                perusahaan.getNamaPerusahaan(),
                kuisioner.getPencacah(),
                kuisioner.getPengawas()
            });
        }
    }
    
    private void clearForm() {
        deleteButton.setVisible(false);
        tampilButton.setVisible(false);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable databaseTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tampilButton;
    // End of variables declaration//GEN-END:variables
}
